export const projects = [
  {
    id: "0",
    title: "Klinik Dr Twins",
    description:
      "Website for Klinik Dr Twins, a clinic that provides medical services to patients.",
    category: "WEB / CLINIC",
    technologies: ["Next.js", "Tailwind CSS", "React", "Node.js"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "CLINIC",
    liveDemoUrl: "https://klinikdrtwins.my",
    codeUrl: "https://github.com/aizuddinahmd/klinikdrtwins",
    imageUrl: "/images/projects/klinikdrtwins.png",
  },
  {
    id: "1",
    title: "The Wellnest Admin Dashboard",
    description:
      "Admin dashboard for The Wellnest, a wellnest centre that provides services for facial, skin, and body treatments. Features include appointment scheduling, patient management, and inventory management.",
    category: "WEB / CLINIC",
    technologies: ["Next.js", "Tailwind CSS", "React", "Node.js"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "ADMIN DASHBOARD",
    liveDemoUrl: "https://the-wellnest-admin.vercel.app/",
    codeUrl: "https://github.com/aizuddinahmd/the-wellnest-admin",
    imageUrl: "/images/projects/thewellnest-admin.png",
  },
  {
    id: "2",
    title: "MYND Portal",
    description:
      "A community building platforn for the tech community in Malaysia. Features include event management tools, learning management system, and a forum for the community to discuss and share their ideas.",
    category: "WEB / COMMUNITY",
    technologies: ["Next.js", "Supabase", "Node.js", "PostgreSQL"],
    moreTechnologies: 2,
    features: [],
    categoryTag: "COMMUNITY",
    liveDemoUrl: "https://skolalab-educhain.vercel.app/",
    codeUrl: "https://github.com/aizuddinahmd/skolalab-educhain",
    imageUrl: "/images/projects/MYND-platform.png",
  },
  {
    id: "3",
    title: "SkolaLab Website",
    description:
      "Official website for Skola Lab Technologies, a community that provides blockchain education to students and professionals.",
    category: "WEB / COMMUNITY",
    technologies: ["Vite.js", "Tailwind CSS", "React", "TypeScript"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "EDUCATION",
    liveDemoUrl: "https://skolalab-landingpage.vercel.app/",
    codeUrl: "https://github.com/aizuddinahmd/skolalab-landingpage",
    imageUrl: "/images/projects/skolalab.png",
  },
  {
    id: "4",
    title: "EUFT Website",
    description:
      "Website for football game called EUFT (European Football Tournament)",
    category: "WEB / COMMUNITY",
    technologies: ["Vite.js", "TypeScript"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "WEBSITE",
    liveDemoUrl: "https://euft-amber.vercel.app/",
    codeUrl: "https://github.com/aizuddinahmd/euft",
    imageUrl: "/images/projects/euft-website.png",
  },
  {
    id: "5",
    title: "TMR Games Website",
    description:
      "Website for TMR Games, a company that provides games for the public.",
    category: "WEB / COMMUNITY",
    technologies: ["Vite.js", "TypeScript"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "WEBSITE",
    liveDemoUrl: "https://tmr-games.vercel.app/",
    codeUrl: "https://github.com/aizuddinahmd/tmr-games",
    imageUrl: "/images/projects/tmr-games.png",
  },
  {
    id: "6",
    title: "LMS Platform",
    description:
      "LMS platform for Skola Labs to provide blockchain education to students and professionals.",
    category: "WEB / COMMUNITY",
    technologies: ["Next.js", "Tailwind CSS", "React", "Node.js"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "EDUCATION",
    liveDemoUrl: "https://kampus-sekolah-kripto.vercel.app/",
    codeUrl: "https://github.com/aizuddinahmd/eduhub-kampus",
    imageUrl: "/assets/projects/lms-platform.png",
  },
  {
    id: "7",
    title: "TWN by Dr Twins",
    description:
      "Website for TWN by Dr Twins, a wellnest center that provides services for facial, skin and body. They also provides pilates classes and become a women's hub",
    category: "WEB / COMMUNITY",
    technologies: ["Next.js", "Tailwind CSS", "React", "Node.js"],
    moreTechnologies: 0,
    features: [],
    categoryTag: "WEBSITE",
    liveDemoUrl: "https://www.thewellnest-bdt.my/",
    codeUrl: "https://github.com/aizuddinahmd/the-wellnest",
    imageUrl: "/images/projects/the-wellnest.png",
  },
];
